### ISSUE TITLE
reword linux distribution page when it comes to wayland and i3

### ISSUE THREAD

**Issue by alexmo1997** [PrivSec-dev/privsec.dev#12]
While `i3` does not support wayland, `sway`, which you recommend above recommending against `i3`, is a drop-in replacement for `i3`and I think this should be made apparent here, so people can switch to that if they are currently using `i3` or planned to use it.

**Comment by tommytran732** [comment]
Done in https://github.com/PrivSec-dev/privsec.dev/commit/d7917bc5a35288e22e017c7da7ed898a5fe2ac40
