### ISSUE TITLE
Dropbear section, ZFS Encryption with Proxmox

### ISSUE THREAD

**Issue by developStorm** [PrivSec-dev/privsec.dev#142]
Thanks for writing [Using Native ZFS Encryption with Proxmox](https://privsec.dev/posts/linux/using-native-zfs-encryption-with-proxmox/)!

A feedback for that article - for reference, in the latest Proxmox 8, I had to place `authorized_keys` and `dropbear.conf` under `/etc/dropbear/initramfs/` for them to work.

```
dropbear-bin/stable,now 2022.83-1 amd64
dropbear-initramfs/stable,now 2022.83-1 all
```

Also, I think it's worth mentioning that dropbear can be configured before encrypting the pool - it would be a _bit_ easier to type in the password 😂.

**Comment by tommytran732** [comment]
Ah okay so just the file location being changed.

**Comment by tommytran732** [comment]
Should be fixed in https://github.com/PrivSec-dev/privsec.dev/commit/7226a9c72fcca7b3c06c66f54089f60bbbd801a7
