### ISSUE TITLE
Windows Guide

### ISSUE THREAD

**Issue by Uncover-Monetize** [PrivSec-dev/privsec.dev#143]
I recommend making a Windows guide to improve everyone's privacy & security. Here are two examples (both of which I assisted making in one capacity or another)

https://thenewoil.org/en/guides/moderately-important/desktop-settings/

https://discuss.privacyguides.net/t/windows-guide/250/4
https://deploy-preview-1659--privacyguides.netlify.app/windows/overview/#issues-present-in-windows
Finally there is the _beerisgood_ guides to consider as well
https://github.com/beerisgood/Windows11_Hardening
https://github.com/beerisgood/Windows11_Privacy

**Comment by wj25czxj47bu6q** [comment]
Superseded by #144.
