### ISSUE TITLE
Update dead links to https://github.com/Kicksecure/security-misc/tree/master/etc/sysctl.d on the Desktop Linux Hardening post

### ISSUE THREAD

**Issue by throwaway43** [PrivSec-dev/privsec.dev#176]
Basically title.

Some personal digging pointed me towards https://github.com/Kicksecure/security-misc/tree/master/usr/lib/sysctl.d/ becoming the new link. I might be wrong though*.

Btw, I love your work! Thank you so much! Much appreciated!

**Comment by friendly-rabbit-35** [comment]
The dead link in question was fixed in #228 and after #232 was merged, there aren't any dead links in the sysctl section anymore.
