### ISSUE TITLE
Docker Hardening: no-new-privileges with different syntax

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [PrivSec-dev/privsec.dev#177]
Advice in https://privsec.dev/posts/linux/docker-and-oci-hardening/#the-no_new_privs-bit works only as

```
    security_opt:
      - "no-new-privileges=true"
```

when I tested it with Docker version 24.0.7 and Docker Compose version v2.21.0.

**Comment by TommyTran732** [comment]
Resolved in https://github.com/PrivSec-dev/privsec.dev/commit/7db27f60748a6ca73c4d2c354037d9d3867ed884
