### ISSUE TITLE
"Mullvad VPN on Qubes OS" guide: include Mullvad repos & Qubes OS 4.2.0 default Xfce templates?

### ISSUE THREAD

**Issue by taivlam** [PrivSec-dev/privsec.dev#196]
I have 2 related suggestions for the guide for the Mullvad VPN on Qubes OS [guide](https://privsec.dev/posts/qubes/using-mullvad-vpn-on-qubes-os/).

1.  Since November 20, 2023, Mullvad VPN is available via package [repositories](https://mullvad.net/en/blog/introducing-package-repositories-for-ubuntu-debian-and-fedora) for Ubuntu/Debian and Fedora.  If possible, I think this update could be worked into the guide.
    * This means that updating Mullvad VPN in the Fedora TemplateVM should be hypothetically easier now, once the repository is set up.
2.  Also, I think the fine details should be verified after Qubes OS [4.2.0](https://www.qubes-os.org/news/2023/12/18/qubes-os-4-2-0-has-been-released/) on December 18, 2023, which includes: "[d]efault Fedora and Debian templates use Xfce instead of GNOME".
    * I'm not sure if this will make removing unneeded packages out of the Fedora TemplateVM easier, based on these changes in Qubes OS 4.2.0, as some readers will be following this guide from a new Qubes OS 4.2.0+ installation.

**Comment by taivlam** [comment]
A new Qubes OS community [guide](https://forum.qubes-os.org/t/mullvad-vpn-app-4-2-setup-guide/25107) has been written for Qubes 4.2.0+, though it's different in approach with a standalone VM, instead of making an AppVM.

**Comment by wj25czxj47bu6q** [comment]
@TommyTran732

**Comment by TommyTran732** [comment]
1. I have updated the guide to use the new Fedora repo. I also made it use systemd path now instead of the rc.local hack, which will update the dns config every time Mullvad changes /etc/resolv.conf.

2. I do not use XFCE and do not have any plans to put efforts into doing it right now. The guide works with Qubes 4.2 with the GNOME template.
