### ISSUE TITLE
Nontrivial changes to the Desktop Linux Hardening page

### ISSUE THREAD

**Issue by friendly-rabbit-35** [PrivSec-dev/privsec.dev#229]
There are other outdated links and dated sections in the Desktop Linux Hardening page (and elsewhere) which I did not address in #228 because any replacements to these broken links would not be simply a drop-in or a matter of just updating a URL. Hence, I opened this issue for further discussion.

## Link(s) up for replacement
- "Kicksecure's apparmor-profile-everything" link points to a GitHub repository that has been archived since mid-January 2024
  - STATUS: WAITING, REQUIRES MORE INVESTIGATION
  - Affected page: https://privsec.dev/posts/linux/desktop-linux-hardening/#making-your-own-policiesprofiles and https://privsec.dev/posts/linux/choosing-your-desktop-linux-distribution/#whonix

## Solved 
  <details>
  <summary>Details here</summary>

- Broken link for "The Ubuntu Security Guide"
  - STATUS: SOLVED by #232 
  - Affected page: https://privsec.dev/posts/linux/desktop-linux-hardening/#ubuntu-pro
  - Looks like there are two links in the same embed: https://github.com/PrivSec-dev/privsec.dev/blob/main/content/posts/linux/Desktop%20Linux%20Hardening.md?plain=1#L201. The link to the Ubuntu Security Guide looks like the appropriate link for this embed, as the other link (to the thread about the Ubuntu Advantage Client) defers to the Ubuntu Pro documentation.
- Broken link for "unprivileged user namespaces"
  - STATUS: SOLVED by #232 
  - Affected page: https://privsec.dev/posts/linux/desktop-linux-hardening/#runtime-kernel-parameters-sysctl
  - Looks like the page that the now-broken link points to is also hosted on GitHub: https://github.com/sangam14/CloudNativeLab/blob/master/LXC/Linux%20Containers/User_namespaces.md. Using an [archived version](https://web.archive.org/web/20230613104252/https://www.containerlabs.kubedaily.com/LXC/Linux%20Containers/User_namespaces.html) of the previous page, I can confirm that the GitHub version contains the same content.
- The Kicksecure wiki now states the following about hardened_malloc in a section titled "[Deprecation in Kicksecure](https://www.kicksecure.com/wiki/Hardened_Malloc#Deprecation_in_Kicksecure)":
    > it has been determined that it will never be stable enough to be suitable for installation by default for all users
  - STATUS: SOLVED by #249
  - Affected page: https://privsec.dev/posts/linux/desktop-linux-hardening/#hardened-memory-allocator
</details>

**Comment by TommyTran732** [comment]
PR merged.
