### ISSUE TITLE
PrivSec.dev WebKit issue

### ISSUE THREAD

**Issue by iiinhoj** [PrivSec-dev/privsec.dev#41]
I'm experiencing some buggy behavior when visiting your site from a WebKit browser—in this case, Safari.

Consecutively clicking through 3 or so pages on your site results in the webpage crashing:

![](https://user-images.githubusercontent.com/88053191/181907747-62969007-24bc-4d06-8bdc-45f95a5e0639.png)

And if it's of any help, these are the error messages that appear in the console:

![](https://user-images.githubusercontent.com/88053191/181907814-40427602-81af-4e1a-b290-5e1697035c87.png)

I haven't experienced any similar issues on other sites, so I do think it's on your guys' end.

**Comment by tommytran732** [comment]
Have you tried on a Chromium based browser?

This is likely a problem with Safari itself, but I would have a closer look later. We dont have any unsafe inline javascript except for the sitemap and index.xml (rss). Thus, the current CSP is to disable unsafe-inline everywhere incept for *.xml.

CC @Wonderfall

**Comment by Wonderfall** [comment]
We need more information: what is your Safari version?

A few days ago I could reproduce the same issue with Safari beta on iOS 16 public beta with COOP/COEP enabled, but not with those disabled.

**Comment by iiinhoj** [comment]
> We need more information

macOS 13 / iOS 16
Safari 16.0 (18614.1.22.1.2)

I also experience the same issue in the Orion browser which uses WebKit 614.1.20.

**Comment by Wonderfall** [comment]
I'm pretty it comes from Safari's COOP implementation. Sadly nothing we can do besides disabling it until they fix it.

**Comment by tommytran732** [comment]
I disabled COOP temporarily

**Comment by beerisgood** [comment]
I can also verify that problem and I don't use any browser extension nor other restrictions.

macOS 12.5 with Safari 15.6

**Comment by Wonderfall** [comment]
@beerisgood Are you saying hat you experienced this issue on https://privsec.dev right now, or before https://github.com/PrivSec-dev/privsec.dev/commit/a43753e5443e50cdae990d559d49b1d989752994?

**Comment by beerisgood** [comment]
@Wonderfall it's fine now 👍
